### ISSUE TITLE
Symbole für z.B. Funkverbindungen lassen sich nicht beliebig skalieren

### ISSUE THREAD

**Issue by jonas-koeritz** [MartinBoehmer/Taktische-Zeichen-drawio#3]
Die Symbole können horizontal nicht gestreckt werden.
`"aspect": "fixed"` verhindert das verzerren der Symbole. Für Symbole wie Funkverbindungen/Betriebsarten kann es gewünscht sein diese lang- zu ziehen.

**Comment by MartinBoehmer** [comment]
Kannst du dafür mal ein konkretes Beispiel nennen bzw. zeigen, bitte? Ich kenne das so, dass die Funk-Symbole durch Linien verbunden werden und nicht "verzerrt" werden müssen.

**Comment by jonas-koeritz** [comment]
Das ist natürlich auch möglich.
