### ISSUE TITLE
Zeichen "DMO Betrieb" und "TMO Betrieb" falsch verlinkt

### ISSUE THREAD

**Issue by vinniep** [MartinBoehmer/Taktische-Zeichen-drawio#6]
Hi,

vielen Dank erst Mal für die Mühe - so ein hilfreiches Tool in einem sehr spärlich abgedecktem Markt...

Mir ist jetzt beim Erstellen eines Kommunikationsplanes aufgefallen, dass die Verlinkung der Zeichen "DMO Betrieb" und "TMO Betrieb" nicht korrekt ist.

Wenn ich die Links aus der letzten Revision rauskopiere, funktionieren die Zeichen noch.

Beste Grüße

**Comment by MartinBoehmer** [comment]
Das liegt wohl an der Skalierbarkeit der Zeichen, vgl. https://github.com/jonas-koeritz/Taktische-Zeichen/issues/52

draw.io scheint das nicht zu verstehen. Ich habe dafür noch keine Lösung.

**Comment by MartinBoehmer** [comment]
Korrektur: Es lag am Transformationsskript. Ist bald behoben.
